-- =============================================================================
-- SomaCore — Phase 1 schema (initial migration, target representation)
-- =============================================================================
--
-- This file is the target representation of the phase-1 schema. The actual
-- migration that creates these objects is generated by EF Core via
-- `dotnet ef migrations add InitialCreate` against entity classes that mirror
-- this shape.
--
-- Why we keep this file alongside the EF Core migrations:
--   - SQL is the most reviewable artifact for a schema. Everyone on the team
--     can read it. Tai reviewed this file before any code was written against it.
--   - When EF Core's generated migration drifts from intent (rare but real),
--     this file is the spec we reconcile against.
--   - When evaluating Timescale, partitioning, or other future evolutions,
--     this file is the starting point for those conversations.
--
-- Conventions in this file:
--   - All identifiers snake_case.
--   - Primary keys are UUID v7 (RFC 9562). On Postgres 18+ we use the native
--     uuidv7() function; on Postgres 16/17 the application generates them
--     and the DEFAULT is omitted (note next to each PK).
--   - Every table has created_at / updated_at, set by the application layer.
--     We deliberately do NOT use triggers for updated_at — keeps the schema
--     transparent and the application in control.
--   - Hard deletes only in phase 1. The privacy policy commits to actual
--     deletion; the schema stays honest with that.
--   - Raw payloads are kept alongside parsed columns for recomputability.
--
-- See ADRs:
--   docs/decisions/0003-postgres-flexible-server.md
--   docs/decisions/0004-ef-core-migrations.md
--   docs/decisions/0006-three-layer-whoop-ingestion.md
--   docs/decisions/0007-key-vault-for-oauth-tokens.md
--   docs/decisions/0009-postgres-backed-work-queue.md
-- =============================================================================


-- -----------------------------------------------------------------------------
-- Extensions
-- -----------------------------------------------------------------------------
-- pgcrypto gives us gen_random_uuid() (UUID v4) as a fallback if we ever need
-- it. UUID v7 is generated either by Postgres 18+ (native uuidv7()) or by the
-- application layer (Npgsql / a small C# helper).
CREATE EXTENSION IF NOT EXISTS pgcrypto;


-- -----------------------------------------------------------------------------
-- Enum-like types (implemented as text columns with CHECK constraints rather
-- than Postgres ENUM types — easier to evolve, easier for EF Core to map)
-- -----------------------------------------------------------------------------
-- Documented values, enforced by CHECK constraints below:
--
--   external_connections.source           : 'whoop' | 'oura' | 'strava' | 'apple_health' | 'manual'
--   external_connections.status           : 'active' | 'revoked' | 'refresh_failed' | 'pending_authorization'
--   whoop_recoveries.score_state          : 'SCORED' | 'PENDING_SCORE' | 'UNSCORABLE'
--   webhook_events.source                 : 'whoop' | 'oura' | 'strava' (phase 1 = whoop only)
--   webhook_events.status                 : 'received' | 'processing' | 'processed' | 'failed' | 'discarded'
--   oauth_audit.action                    : 'authorize' | 'callback_success' | 'callback_failed' |
--                                            'token_refresh_success' | 'token_refresh_failed' |
--                                            'revoke_detected' | 'manual_disconnect'
--
-- We use text + CHECK rather than CREATE TYPE ... AS ENUM because:
--   - Adding a new value to a Postgres ENUM in a transaction is restrictive
--     (cannot use the new value in the same transaction as adding it).
--   - EF Core's mapping for Postgres ENUMs requires extra configuration vs
--     a simple string mapping.
--   - Changing CHECK constraints is cheap; evolving ENUM types is annoying.


-- =============================================================================
-- TABLE: users
--
-- One row per SomaCore user. Keyed by Entra OID — the immutable object ID
-- issued by Entra ID on first sign-in. We JIT-create the row when a user
-- first authenticates.
--
-- WHOOP, Oura, Strava, etc. live in `external_connections`, NOT here. The
-- user record is identity-and-profile only; integration state belongs to
-- the connection.
-- =============================================================================
CREATE TABLE users (
    id                  uuid PRIMARY KEY,                  -- UUID v7, app-generated (Postgres 16/17) or DEFAULT uuidv7() (PG18+)
    entra_oid           uuid NOT NULL UNIQUE,              -- Entra Object ID. Immutable, the spine of identity.
    entra_tenant_id     uuid NOT NULL,                     -- Tenant the user authenticated against. Phase 1 = tento100.com tenant only.
    email               text NOT NULL,                     -- From Entra; mutable, kept for human-readable lookup.
    display_name        text,                              -- From Entra; nullable because not all profiles have one.

    -- Timestamps managed by the application layer.
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    last_seen_at        timestamptz                        -- Updated on each authenticated request.
);

-- Index for the email lookup path (admin tooling, support).
CREATE INDEX idx_users_email ON users (lower(email));


-- =============================================================================
-- TABLE: external_connections
--
-- One row per (user, source) pair. Holds the OAuth state and metadata for
-- each external integration the user has connected.
--
-- Tokens themselves are NEVER in this table — the `key_vault_secret_name`
-- column points at an Azure Key Vault secret which holds the refresh token.
-- See ADR 0007.
--
-- The `connection_metadata` jsonb is for source-specific fields that don't
-- justify their own column yet. WHOOP-specific shape:
--   {
--     "whoop_user_id": 12345678,
--     "whoop_email": "user@example.com"   // returned by WHOOP /user/profile/basic
--   }
-- Oura, Strava, etc. will add their own keys later. We deliberately keep
-- common fields (status, scopes, refresh metadata) as columns rather than
-- buried in jsonb — they're queried often and we want them indexable.
-- =============================================================================
CREATE TABLE external_connections (
    id                          uuid PRIMARY KEY,           -- UUID v7
    user_id                     uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    source                      text NOT NULL,              -- 'whoop' in phase 1
    status                      text NOT NULL,              -- see enum-like comment above
    scopes                      text[] NOT NULL DEFAULT '{}',

    -- Pointer to the refresh token in Key Vault. NEVER store token values here.
    key_vault_secret_name       text NOT NULL,

    -- Refresh metadata. We track these to debug refresh failures and to
    -- decide when to proactively refresh (every ~50 min for WHOOP).
    last_refresh_at             timestamptz,
    next_refresh_at             timestamptz,                -- Hint for the refresh sweeper; not authoritative.
    refresh_failure_count       int NOT NULL DEFAULT 0,
    last_refresh_error          text,                       -- Truncated to ~500 chars at write time.

    -- Source-specific fields that don't warrant their own columns yet.
    connection_metadata         jsonb NOT NULL DEFAULT '{}'::jsonb,

    created_at                  timestamptz NOT NULL DEFAULT now(),
    updated_at                  timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT chk_external_connections_source
        CHECK (source IN ('whoop', 'oura', 'strava', 'apple_health', 'manual')),
    CONSTRAINT chk_external_connections_status
        CHECK (status IN ('active', 'revoked', 'refresh_failed', 'pending_authorization')),

    -- A user can only have one active connection per source. We use a partial
    -- unique index rather than a table-level UNIQUE constraint so that revoked
    -- and pending connections don't block re-authorization.
    -- (This is added below as a partial unique index.)
    CONSTRAINT chk_external_connections_kv_secret_name_not_empty
        CHECK (length(key_vault_secret_name) > 0)
);

-- One ACTIVE connection per (user, source). Other statuses can coexist.
CREATE UNIQUE INDEX idx_external_connections_user_source_active
    ON external_connections (user_id, source)
    WHERE status = 'active';

-- Lookup path for the refresh sweeper: "find connections due for refresh".
CREATE INDEX idx_external_connections_next_refresh
    ON external_connections (next_refresh_at)
    WHERE status = 'active';

-- Lookup path for finding all connections for a user (e.g., on /me page load).
CREATE INDEX idx_external_connections_user_id
    ON external_connections (user_id);


-- =============================================================================
-- TABLE: whoop_recoveries
--
-- One row per WHOOP recovery event. Recoveries are uniquely identified by
-- the WHOOP cycle they belong to — `whoop_cycle_id` is the natural key from
-- WHOOP's side. We dedupe on (external_connection_id, whoop_cycle_id) so
-- repeated webhook deliveries or poller fetches converge on a single row.
--
-- score_state can be SCORED, PENDING_SCORE, or UNSCORABLE — we store rows
-- in all three states. The score / HRV / RHR columns are nullable because
-- PENDING_SCORE and UNSCORABLE rows don't carry them.
--
-- raw_payload holds the exact JSON WHOOP returned. This is what makes the
-- pipeline recomputable: if we discover we should have been parsing
-- something differently, we replay from raw without re-fetching.
-- =============================================================================
CREATE TABLE whoop_recoveries (
    id                          uuid PRIMARY KEY,           -- UUID v7
    user_id                     uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    external_connection_id      uuid NOT NULL REFERENCES external_connections(id) ON DELETE CASCADE,

    -- Natural keys from WHOOP.
    whoop_cycle_id              bigint NOT NULL,            -- WHOOP cycle this recovery belongs to.
    whoop_sleep_id              uuid,                       -- v2 webhooks identify recoveries by sleep UUID; nullable for poller-fetched rows.

    -- The headline fields. Nullable when score_state != 'SCORED'.
    score_state                 text NOT NULL,
    recovery_score              int,                        -- 0-100. WHOOP returns int.
    hrv_rmssd_milli             numeric(10, 4),             -- HRV RMSSD in milliseconds. Up to 4 decimal places.
    resting_heart_rate          int,                        -- BPM. WHOOP returns int.
    spo2_percentage             numeric(5, 2),              -- 0-100. Optional in WHOOP response.
    skin_temp_celsius           numeric(5, 2),              -- Optional in WHOOP response.

    -- The cycle window this recovery describes. WHOOP defines a cycle as the
    -- period between two sleeps; the recovery is the score for that window.
    cycle_start_at              timestamptz NOT NULL,
    cycle_end_at                timestamptz,                -- Null for in-progress cycles (rare for SCORED, common for PENDING).

    -- Provenance: which ingestion path landed this row, and when.
    ingested_via                text NOT NULL,              -- 'webhook' | 'poller' | 'on_open_pull'
    ingested_at                 timestamptz NOT NULL DEFAULT now(),

    -- The exact WHOOP API response that produced this row.
    raw_payload                 jsonb NOT NULL,

    created_at                  timestamptz NOT NULL DEFAULT now(),
    updated_at                  timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT chk_whoop_recoveries_score_state
        CHECK (score_state IN ('SCORED', 'PENDING_SCORE', 'UNSCORABLE')),
    CONSTRAINT chk_whoop_recoveries_ingested_via
        CHECK (ingested_via IN ('webhook', 'poller', 'on_open_pull')),
    CONSTRAINT chk_whoop_recoveries_score_range
        CHECK (recovery_score IS NULL OR (recovery_score BETWEEN 0 AND 100)),
    CONSTRAINT chk_whoop_recoveries_spo2_range
        CHECK (spo2_percentage IS NULL OR (spo2_percentage BETWEEN 0 AND 100)),
    -- A SCORED row must carry the headline fields. PENDING/UNSCORABLE rows must not pretend.
    CONSTRAINT chk_whoop_recoveries_scored_has_score
        CHECK (
            (score_state = 'SCORED' AND recovery_score IS NOT NULL)
            OR
            (score_state IN ('PENDING_SCORE', 'UNSCORABLE'))
        )
);

-- Idempotency / dedupe: one row per (connection, cycle).
-- All three ingestion paths converge here.
CREATE UNIQUE INDEX idx_whoop_recoveries_connection_cycle
    ON whoop_recoveries (external_connection_id, whoop_cycle_id);

-- Hot-path query for /me: "give me this user's recent recoveries".
CREATE INDEX idx_whoop_recoveries_user_cycle_start
    ON whoop_recoveries (user_id, cycle_start_at DESC);

-- Lookup by sleep ID (the webhook payload identifies recoveries by sleep UUID).
CREATE INDEX idx_whoop_recoveries_sleep_id
    ON whoop_recoveries (whoop_sleep_id)
    WHERE whoop_sleep_id IS NOT NULL;


-- =============================================================================
-- TABLE: webhook_events
--
-- One row per webhook received. Serves three purposes simultaneously:
--   1. Idempotency: dedupe by (source, source_event_id, source_trace_id).
--   2. Audit trail: every webhook is recorded, regardless of outcome.
--   3. Work queue: rows in 'received' status are picked up by the
--      background worker and processed. See ADR 0009.
--
-- raw_body holds the exact bytes WHOOP POSTed (after HMAC validation).
-- This is the source of truth for replay — if processing has a bug, we
-- can re-run the worker against the stored bodies.
--
-- We store the raw_body even though the architecture says webhooks carry
-- only IDs (the actual data is fetched via REST). Storage cost is trivial,
-- debugging value is real.
-- =============================================================================
CREATE TABLE webhook_events (
    id                          uuid PRIMARY KEY,           -- UUID v7
    source                      text NOT NULL,              -- 'whoop' in phase 1
    source_event_id             text NOT NULL,              -- WHOOP's `id` field (the sleep UUID for recovery events)
    source_trace_id             text NOT NULL,              -- WHOOP's `trace_id` field
    event_type                  text NOT NULL,              -- e.g. 'recovery.updated'

    -- The user this event is for. Nullable because in rare cases we may
    -- receive a webhook for a user we don't have in our DB (shouldn't
    -- happen with a private dev app, but the audit trail is more useful
    -- if we record it anyway).
    user_id                     uuid REFERENCES users(id) ON DELETE SET NULL,
    external_connection_id      uuid REFERENCES external_connections(id) ON DELETE SET NULL,

    -- Status drives the work queue. See ADR 0009.
    status                      text NOT NULL DEFAULT 'received',
    received_at                 timestamptz NOT NULL DEFAULT now(),
    processing_started_at       timestamptz,
    processed_at                timestamptz,
    processing_attempts         int NOT NULL DEFAULT 0,
    last_error                  text,                       -- Truncated to ~2000 chars at write time.

    -- The exact request that arrived. Useful for debugging and replay.
    raw_body                    jsonb NOT NULL,
    signature_header            text NOT NULL,              -- The X-WHOOP-Signature value we validated against.
    signature_timestamp_header  text NOT NULL,              -- The timestamp header used in HMAC.

    created_at                  timestamptz NOT NULL DEFAULT now(),
    updated_at                  timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT chk_webhook_events_source
        CHECK (source IN ('whoop', 'oura', 'strava')),
    CONSTRAINT chk_webhook_events_status
        CHECK (status IN ('received', 'processing', 'processed', 'failed', 'discarded'))
);

-- Idempotency: WHOOP can deliver the same event twice.
-- (source, source_event_id, source_trace_id) is unique.
CREATE UNIQUE INDEX idx_webhook_events_dedupe
    ON webhook_events (source, source_event_id, source_trace_id);

-- Work queue path: "give me the next batch of unprocessed events".
-- Partial index keeps it tiny — only rows actually waiting to be processed.
CREATE INDEX idx_webhook_events_pending
    ON webhook_events (received_at)
    WHERE status IN ('received', 'processing');

-- Audit lookup: "all events for this user, recent first".
CREATE INDEX idx_webhook_events_user_received
    ON webhook_events (user_id, received_at DESC)
    WHERE user_id IS NOT NULL;


-- =============================================================================
-- TABLE: oauth_audit
--
-- One row per significant OAuth-related action. Used to debug refresh
-- failures, detect revocations, and reconstruct what happened when a
-- connection breaks.
--
-- Distinct from webhook_events — this table tracks our outbound OAuth
-- activity (token refresh, callback handling, revocation detection),
-- not inbound webhook deliveries.
-- =============================================================================
CREATE TABLE oauth_audit (
    id                          uuid PRIMARY KEY,           -- UUID v7
    user_id                     uuid REFERENCES users(id) ON DELETE SET NULL,
    external_connection_id      uuid REFERENCES external_connections(id) ON DELETE SET NULL,
    source                      text NOT NULL,
    action                      text NOT NULL,
    success                     boolean NOT NULL,
    http_status_code            int,                        -- For network actions, the HTTP status. Null for non-network actions.
    error_message               text,                       -- Truncated to ~1000 chars at write time. Never contains tokens.

    -- Context. Free-form jsonb for action-specific details
    -- (e.g. requested scopes for an authorize action, refreshed scopes for a
    -- refresh action). Never contains tokens or secrets.
    context                     jsonb NOT NULL DEFAULT '{}'::jsonb,

    occurred_at                 timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT chk_oauth_audit_source
        CHECK (source IN ('whoop', 'oura', 'strava', 'apple_health')),
    CONSTRAINT chk_oauth_audit_action
        CHECK (action IN (
            'authorize',
            'callback_success',
            'callback_failed',
            'token_refresh_success',
            'token_refresh_failed',
            'revoke_detected',
            'manual_disconnect'
        ))
);

-- Lookup path: "all OAuth events for this user, recent first".
CREATE INDEX idx_oauth_audit_user_occurred
    ON oauth_audit (user_id, occurred_at DESC)
    WHERE user_id IS NOT NULL;

-- Lookup path: "what happened to this connection lately?"
CREATE INDEX idx_oauth_audit_connection_occurred
    ON oauth_audit (external_connection_id, occurred_at DESC)
    WHERE external_connection_id IS NOT NULL;


-- =============================================================================
-- End of phase-1 schema
--
-- Tables: users, external_connections, whoop_recoveries, webhook_events,
--         oauth_audit
-- Total: 5 tables, ~13 indexes (incl. unique constraints).
--
-- Phase 2 will extend this with:
--   - whoop_sleeps, whoop_workouts, whoop_cycles (same pattern as recoveries)
--   - oura_*, strava_*, apple_health_* tables
--   - normalized physiological state snapshots
--   - rules-engine plan outputs
--   - adherence events
-- =============================================================================
