-- =============================================================================
-- SomaCore — Phase 2, Track A: WHOOP sleep + workout schema extension
-- =============================================================================
--
-- Adds two new tables to hold WHOOP v2 sleep and workout objects alongside the
-- existing whoop_recoveries table. Recovery and sleep arrive together via the
-- WHOOP v2 cycle endpoint; workout has its own webhook. From the database's
-- point of view they are independent rows tied to (user_id, external_connection_id).
--
-- This file is the target representation of the migration generated by EF Core
-- (`AddWhoopSleepsAndWorkouts`). Same convention as 0001_initial_schema.sql:
-- the SQL file is the spec that the team reviews; the EF migration is what
-- actually executes. When the two drift, this file is the spec we reconcile
-- against.
--
-- Both tables mirror the whoop_recoveries shape:
--   - UUID v7 primary key (app-generated on PG 16/17; uuidv7() on PG18+)
--   - user_id FK         ON DELETE CASCADE   (full-account deletion removes history)
--   - external_connection_id FK ON DELETE SET NULL (disconnect severs integration,
--                                                   not data — see docs/privacy-data-handling.md)
--   - score_state text  + CHECK constraint   (matches whoop_recoveries.score_state)
--   - raw_payload jsonb                      (recomputability: keep WHOOP's exact response)
--   - ingested_via + ingested_at             (provenance, same vocabulary as recoveries)
--   - created_at / updated_at                (application-managed, no triggers)
--
-- The WHOOP-side identifier (sleep UUID, workout UUID) is stored separately from
-- the local PK and uniqueness is scored to (external_connection_id, whoop_*_id)
-- so the three ingestion paths converge on a single row, identically to recoveries.
--
-- timezone_offset is stored as the literal WHOOP string (e.g. "-07:00", "+00:00").
-- Storing the offset lets us reason about local-time scheduling without re-deriving
-- it from start/end (which arrive in UTC).
-- =============================================================================


-- =============================================================================
-- TABLE: whoop_sleeps
--
-- One row per WHOOP sleep object. Each cycle has one main sleep plus zero or
-- more naps; `nap = true` identifies the latter. WHOOP returns sleep with a
-- score state and (when scored) a structured score breakdown — we lift the
-- four headline percentages and the two in-bed/asleep millisecond counters
-- into typed columns, keep the rest in `score` jsonb.
--
-- WHOOP v2 field mapping notes:
--   - `id` (UUID)               → whoop_sleep_id
--   - `start` / `end` (UTC)     → start_at / end_at
--   - `timezone_offset` (str)   → timezone_offset
--   - `nap` (bool)              → nap
--   - `score_state` (enum)      → score_state
--   - `score.sleep_performance_percentage`     → sleep_performance_percentage
--   - `score.sleep_efficiency_percentage`      → sleep_efficiency_percentage
--   - `score.sleep_consistency_percentage`     → sleep_consistency_percentage
--   - `score.stage_summary.total_in_bed_time_milli`  → total_in_bed_time_milli
--   - `score.stage_summary.total_in_bed_time_milli`+ asleep equivalent → total_sleep_time_milli
--     (i.e. `total_in_bed_time_milli` minus awake; or sum of light/SWS/REM)
--   - full `score` object       → score (jsonb)
--   - the entire WHOOP response → raw_payload (jsonb)
--
-- Both percentages and millisecond counters are nullable: PENDING_SCORE and
-- UNSCORABLE rows do not carry score fields.
-- =============================================================================
CREATE TABLE whoop_sleeps (
    id                              uuid PRIMARY KEY,           -- UUID v7
    user_id                         uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    -- ON DELETE SET NULL: disconnect severs the integration, not the data.
    -- Same contract as whoop_recoveries.external_connection_id.
    external_connection_id          uuid REFERENCES external_connections(id) ON DELETE SET NULL,

    -- Natural key from WHOOP.
    whoop_sleep_id                  uuid NOT NULL,              -- WHOOP sleep object UUID.

    -- The sleep window. WHOOP returns these in UTC; timezone_offset is the
    -- user-facing wall-clock offset for the night the sleep belongs to.
    start_at                        timestamptz NOT NULL,
    end_at                          timestamptz NOT NULL,
    timezone_offset                 text NOT NULL,              -- e.g. "-07:00" — literal WHOOP value.

    nap                             boolean NOT NULL,

    -- Score state and lifted score fields. Nullable when score_state != 'SCORED'.
    score_state                     text NOT NULL,
    sleep_performance_percentage    numeric(5, 2),              -- 0-100.
    sleep_efficiency_percentage     numeric(5, 2),              -- 0-100.
    sleep_consistency_percentage    numeric(5, 2),              -- 0-100.
    total_in_bed_time_milli         bigint,                     -- WHOOP returns milliseconds.
    total_sleep_time_milli          bigint,                     -- Total asleep (in-bed minus awake).

    -- Full WHOOP score object (jsonb), preserved alongside the lifted columns so
    -- we can derive new fields later from raw without re-fetching.
    score                           jsonb,                      -- Nullable when score_state != 'SCORED'.

    -- Provenance.
    ingested_via                    text NOT NULL,              -- 'webhook' | 'poller' | 'on_open_pull'
    ingested_at                     timestamptz NOT NULL DEFAULT now(),

    -- The exact WHOOP API response that produced this row.
    raw_payload                     jsonb NOT NULL,

    created_at                      timestamptz NOT NULL DEFAULT now(),
    updated_at                      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT chk_whoop_sleeps_score_state
        CHECK (score_state IN ('SCORED', 'PENDING_SCORE', 'UNSCORABLE')),
    CONSTRAINT chk_whoop_sleeps_ingested_via
        CHECK (ingested_via IN ('webhook', 'poller', 'on_open_pull')),
    CONSTRAINT chk_whoop_sleeps_perf_range
        CHECK (sleep_performance_percentage IS NULL
               OR (sleep_performance_percentage BETWEEN 0 AND 100)),
    CONSTRAINT chk_whoop_sleeps_eff_range
        CHECK (sleep_efficiency_percentage IS NULL
               OR (sleep_efficiency_percentage BETWEEN 0 AND 100)),
    CONSTRAINT chk_whoop_sleeps_cons_range
        CHECK (sleep_consistency_percentage IS NULL
               OR (sleep_consistency_percentage BETWEEN 0 AND 100))
);

-- Idempotency / dedupe: one row per (connection, whoop sleep id).
-- All three ingestion paths converge here.
CREATE UNIQUE INDEX idx_whoop_sleeps_connection_sleep
    ON whoop_sleeps (external_connection_id, whoop_sleep_id);

-- Hot-path query for /me and the rules engine: this user's recent sleeps.
CREATE INDEX idx_whoop_sleeps_user_start
    ON whoop_sleeps (user_id, start_at DESC);


-- =============================================================================
-- TABLE: whoop_workouts
--
-- One row per WHOOP workout. WHOOP v2 identifies the sport by `sport_name`
-- (string) rather than the legacy integer `sport_id`. We store the name as
-- the canonical sport identifier; if WHOOP later ships a richer taxonomy we
-- can derive it from raw_payload.
--
-- WHOOP v2 field mapping notes:
--   - `id` (UUID)               → whoop_workout_id
--   - `start` / `end` (UTC)     → start_at / end_at
--   - `timezone_offset` (str)   → timezone_offset
--   - `sport_name` (str)        → sport_name
--   - `score_state` (enum)      → score_state
--   - `score.strain` (float)    → strain
--   - `score.average_heart_rate` (int)  → average_heart_rate
--   - `score.max_heart_rate` (int)      → max_heart_rate
--   - `score.kilojoule` (float) → kilojoule
--   - full `score` object       → score (jsonb)
--   - the entire WHOOP response → raw_payload (jsonb)
-- =============================================================================
CREATE TABLE whoop_workouts (
    id                              uuid PRIMARY KEY,           -- UUID v7
    user_id                         uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    -- ON DELETE SET NULL: disconnect severs the integration, not the data.
    external_connection_id          uuid REFERENCES external_connections(id) ON DELETE SET NULL,

    -- Natural key from WHOOP.
    whoop_workout_id                uuid NOT NULL,              -- WHOOP workout object UUID.

    -- The workout window.
    start_at                        timestamptz NOT NULL,
    end_at                          timestamptz NOT NULL,
    timezone_offset                 text NOT NULL,

    -- v2: WHOOP returns the sport as a string name rather than an integer id.
    sport_name                      text NOT NULL,

    -- Score state and lifted score fields. Nullable when score_state != 'SCORED'.
    score_state                     text NOT NULL,
    strain                          numeric(6, 4),              -- WHOOP strain is 0..21 with several decimals.
    average_heart_rate              int,                        -- BPM.
    max_heart_rate                  int,                        -- BPM.
    kilojoule                       numeric(10, 4),             -- Energy expenditure.

    -- Full WHOOP score object, preserved alongside the lifted columns.
    score                           jsonb,                      -- Nullable when score_state != 'SCORED'.

    -- Provenance.
    ingested_via                    text NOT NULL,              -- 'webhook' | 'poller' | 'on_open_pull'
    ingested_at                     timestamptz NOT NULL DEFAULT now(),

    -- The exact WHOOP API response that produced this row.
    raw_payload                     jsonb NOT NULL,

    created_at                      timestamptz NOT NULL DEFAULT now(),
    updated_at                      timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT chk_whoop_workouts_score_state
        CHECK (score_state IN ('SCORED', 'PENDING_SCORE', 'UNSCORABLE')),
    CONSTRAINT chk_whoop_workouts_ingested_via
        CHECK (ingested_via IN ('webhook', 'poller', 'on_open_pull')),
    CONSTRAINT chk_whoop_workouts_strain_range
        CHECK (strain IS NULL OR (strain BETWEEN 0 AND 21)),
    CONSTRAINT chk_whoop_workouts_avg_hr_range
        CHECK (average_heart_rate IS NULL OR (average_heart_rate BETWEEN 0 AND 300)),
    CONSTRAINT chk_whoop_workouts_max_hr_range
        CHECK (max_heart_rate IS NULL OR (max_heart_rate BETWEEN 0 AND 300))
);

-- Idempotency / dedupe: one row per (connection, whoop workout id).
CREATE UNIQUE INDEX idx_whoop_workouts_connection_workout
    ON whoop_workouts (external_connection_id, whoop_workout_id);

-- Hot-path query: this user's recent workouts.
CREATE INDEX idx_whoop_workouts_user_start
    ON whoop_workouts (user_id, start_at DESC);


-- =============================================================================
-- End of phase-2 track-A schema extension
--
-- Added tables: whoop_sleeps, whoop_workouts
-- Added indexes: 4 (2 unique dedupe + 2 user/start time-series access)
--
-- Sessions 2-5 will add the ingestion handlers and webhook routing on top of
-- this foundation — same handler-per-source pattern as whoop_recoveries.
-- =============================================================================
