// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SomaCore.Infrastructure.Persistence;

#nullable disable

namespace SomaCore.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SomaCoreDbContext))]
    [Migration("20260712150148_AddStravaActivities")]
    partial class AddStravaActivities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SomaCore.Domain.Agent.AgentInvocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonDocument>("ActionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("actions_json");

                    b.Property<int?>("CachedInputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("cached_input_tokens");

                    b.Property<decimal?>("CostEstimateUsd")
                        .HasPrecision(10, 6)
                        .HasColumnType("numeric(10,6)")
                        .HasColumnName("cost_estimate_usd");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<JsonDocument>("InputSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("input_snapshot");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("daily_card")
                        .HasColumnName("kind");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model_id");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<string>("TodaysRead")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("todays_read");

                    b.Property<string>("TraceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("trace_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_agent_invocations");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_agent_invocations_user_created");

                    b.ToTable("agent_invocations", (string)null);
                });

            modelBuilder.Entity("SomaCore.Domain.CoachThreads.CoachMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("InvocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invocation_id");

                    b.Property<bool>("Refusal")
                        .HasColumnType("boolean")
                        .HasColumnName("refusal");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("ThreadId")
                        .HasColumnType("uuid")
                        .HasColumnName("thread_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_coach_messages");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_coach_messages_user_id");

                    b.HasIndex("ThreadId", "CreatedAt")
                        .HasDatabaseName("idx_coach_messages_thread_created");

                    b.ToTable("coach_messages", null, t =>
                        {
                            t.HasCheckConstraint("chk_coach_messages_role", "role IN ('user', 'coach')");
                        });
                });

            modelBuilder.Entity("SomaCore.Domain.CoachThreads.CoachThread", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("LastMessageAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_message_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_coach_threads");

                    b.HasIndex("UserId", "LastMessageAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_coach_threads_user_last_message");

                    b.ToTable("coach_threads", null, t =>
                        {
                            t.HasCheckConstraint("chk_coach_threads_subject_type", "subject_type IN ('document', 'meal', 'workout', 'note', 'general')");
                        });
                });

            modelBuilder.Entity("SomaCore.Domain.ExternalConnections.ExternalConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonDocument>("ConnectionMetadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("connection_metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("KeyVaultSecretName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_vault_secret_name");

                    b.Property<string>("LastPollOutcome")
                        .HasColumnType("text")
                        .HasColumnName("last_poll_outcome");

                    b.Property<DateTimeOffset?>("LastPolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_polled_at");

                    b.Property<DateTimeOffset?>("LastRefreshAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_refresh_at");

                    b.Property<string>("LastRefreshError")
                        .HasColumnType("text")
                        .HasColumnName("last_refresh_error");

                    b.Property<DateTimeOffset?>("NextRefreshAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_refresh_at");

                    b.Property<int>("RefreshFailureCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("refresh_failure_count");

                    b.PrimitiveCollection<string[]>("Scopes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("scopes")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_external_connections");

                    b.HasIndex("NextRefreshAt")
                        .HasDatabaseName("idx_external_connections_next_refresh")
                        .HasFilter("status = 'active'");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_external_connections_user_id");

                    b.HasIndex("UserId", "Source")
                        .IsUnique()
                        .HasDatabaseName("idx_external_connections_user_source_active")
                        .HasFilter("status = 'active'");

                    b.ToTable("external_connections", null, t =>
                        {
                            t.HasCheckConstraint("chk_external_connections_kv_secret_name_not_empty", "length(key_vault_secret_name) > 0");

                            t.HasCheckConstraint("chk_external_connections_last_poll_outcome", "last_poll_outcome IS NULL OR last_poll_outcome IN ('Skipped', 'Polled', 'Failed')");

                            t.HasCheckConstraint("chk_external_connections_source", "source IN ('whoop', 'oura', 'strava', 'apple_health', 'manual')");

                            t.HasCheckConstraint("chk_external_connections_status", "status IN ('active', 'revoked', 'refresh_failed', 'pending_authorization')");
                        });
                });

            modelBuilder.Entity("SomaCore.Domain.FoodEntries.FoodEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("Calories")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("calories");

                    b.Property<decimal?>("CarbsG")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("carbs_g");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("ExternalConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_connection_id");

                    b.Property<decimal?>("FatG")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("fat_g");

                    b.Property<decimal?>("FiberG")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("fiber_g");

                    b.Property<JsonDocument>("FoodItems")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("food_items");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("IngestedVia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ingested_via");

                    b.Property<DateTimeOffset?>("LoggedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_at");

                    b.Property<DateOnly>("MealDate")
                        .HasColumnType("date")
                        .HasColumnName("meal_date");

                    b.Property<string>("MealSlot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meal_slot");

                    b.Property<decimal?>("ProteinG")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("protein_g");

                    b.Property<JsonDocument>("RawPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<decimal?>("SodiumMg")
                        .HasPrecision(9, 2)
                        .HasColumnType("numeric(9,2)")
                        .HasColumnName("sodium_mg");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<decimal?>("SugarG")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("sugar_g");

                    b.Property<string>("TraceId")
                        .HasColumnType("text")
                        .HasColumnName("trace_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_mfp_food_entries");

                    b.HasIndex("ExternalConnectionId")
                        .HasDatabaseName("ix_mfp_food_entries_external_connection_id");

                    b.HasIndex("UserId", "MealDate")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_mfp_food_entries_user_date");

                    b.HasIndex("UserId", "MealDate", "MealSlot", "Source")
                        .IsUnique()
                        .HasDatabaseName("idx_mfp_food_entries_user_date_slot_source");

                    b.ToTable("mfp_food_entries", null, t =>
                        {
                            t.HasCheckConstraint("chk_mfp_food_entries_calories_range", "calories IS NULL OR (calories BETWEEN 0 AND 20000)");

                            t.HasCheckConstraint("chk_mfp_food_entries_meal_slot", "meal_slot IN ('breakfast', 'lunch', 'dinner', 'snack', 'other')");

                            t.HasCheckConstraint("chk_mfp_food_entries_source", "source IN ('manual', 'healthkit_ios', 'csv_upload')");
                        });
                });

            modelBuilder.Entity("SomaCore.Domain.HealthKitWorkouts.HealthKitWorkout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AverageHr")
                        .HasColumnType("integer")
                        .HasColumnName("average_hr");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("ElapsedSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("elapsed_seconds");

                    b.Property<JsonDocument>("HkMetadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("hk_metadata");

                    b.Property<Guid>("HkSampleUuid")
                        .HasColumnType("uuid")
                        .HasColumnName("hk_sample_uuid");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("SourceBundleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_bundle_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<decimal?>("TotalDistanceM")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_distance_m");

                    b.Property<decimal?>("TotalEnergyKcal")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("total_energy_kcal");

                    b.Property<string>("TraceId")
                        .HasColumnType("text")
                        .HasColumnName("trace_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("WorkoutType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("workout_type");

                    b.HasKey("Id")
                        .HasName("pk_healthkit_workouts");

                    b.HasIndex("HkSampleUuid")
                        .IsUnique()
                        .HasDatabaseName("idx_healthkit_workouts_sample_uuid");

                    b.HasIndex("UserId", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_healthkit_workouts_user_started");

                    b.ToTable("healthkit_workouts", null, t =>
                        {
                            t.HasCheckConstraint("chk_healthkit_workouts_avg_hr_range", "average_hr IS NULL OR (average_hr BETWEEN 0 AND 300)");

                            t.HasCheckConstraint("chk_healthkit_workouts_elapsed_positive", "elapsed_seconds > 0");
                        });
                });

            modelBuilder.Entity("SomaCore.Domain.JobRuns.JobRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_name");

                    b.Property<DateTimeOffset>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool?>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<JsonDocument>("Summary")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("summary")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.HasKey("Id")
                        .HasName("pk_job_runs");

                    b.HasIndex("JobName", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_job_runs_job_started");

                    b.ToTable("job_runs", null, t =>
                        {
                            t.HasCheckConstraint("chk_job_runs_job_name", "job_name IN ('reconciliation-poller', 'token-refresh-sweeper')");
                        });
                });

            modelBuilder.Entity("SomaCore.Domain.LabUploads.LabBiomarker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BiomarkerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("biomarker_name");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateOnly>("CollectedAt")
                        .HasColumnType("date")
                        .HasColumnName("collected_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Flagged")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flagged");

                    b.Property<Guid>("LabUploadId")
                        .HasColumnType("uuid")
                        .HasColumnName("lab_upload_id");

                    b.Property<decimal?>("NumericValue")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("numeric_value");

                    b.Property<decimal?>("ReferenceHigh")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("reference_high");

                    b.Property<decimal?>("ReferenceLow")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("reference_low");

                    b.Property<string>("ReferenceString")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_string");

                    b.Property<string>("StringValue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("string_value");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_lab_biomarkers");

                    b.HasIndex("LabUploadId")
                        .HasDatabaseName("ix_lab_biomarkers_lab_upload_id");

                    b.HasIndex("UserId", "BiomarkerName", "CollectedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("idx_lab_biomarkers_user_marker");

                    b.ToTable("lab_biomarkers", null, t =>
                        {
                            t.HasCheckConstraint("chk_lab_biomarkers_flagged", "flagged IN ('in_range', 'low', 'high', 'unknown')");
                        });
                });

            modelBuilder.Entity("SomaCore.Domain.LabUploads.LabUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("CollectedAt")
                        .HasColumnType("date")
                        .HasColumnName("collected_at");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<Guid?>("ConfirmedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("confirmed_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<byte[]>("FileBytes")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("file_bytes");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<int>("FileSize")
                        .HasColumnType("integer")
                        .HasColumnName("file_size");

                    b.Property<string>("ParseError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("parse_error");

                    b.Property<string>("ParseStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parse_status");

                    b.Property<DateTimeOffset?>("ParsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("parsed_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("TraceId")
                        .HasColumnType("text")
                        .HasColumnName("trace_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_lab_uploads");

                    b.HasIndex("UserId", "Source", "CollectedAt")
                        .IsUnique()
                        .HasDatabaseName("idx_lab_uploads_user_collected");

                    b.ToTable("lab_uploads", null, t =>
                        {
                            t.HasCheckConstraint("chk_lab_uploads_file_size", "file_size > 0 AND file_size <= 10485760");

                            t.HasCheckConstraint("chk_lab_uploads_parse_status", "parse_status IN ('parsed', 'failed', 'confirmed')");
                        });
                });

            modelBuilder.Entity("SomaCore.Domain.OAuthAudit.OAuthAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<JsonDocument>("Context")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("context")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<Guid?>("ExternalConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_connection_id");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("http_status_code");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_oauth_audit");

                    b.HasIndex("ExternalConnectionId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_oauth_audit_connection_occurred")
                        .HasFilter("external_connection_id IS NOT NULL");

                    b.HasIndex("UserId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_oauth_audit_user_occurred")
                        .HasFilter("user_id IS NOT NULL");

                    b.ToTable("oauth_audit", null, t =>
                        {
                            t.HasCheckConstraint("chk_oauth_audit_action", "action IN ('authorize', 'callback_success', 'callback_failed', 'token_refresh_success', 'token_refresh_failed', 'revoke_detected', 'manual_disconnect', 'backfill')");

                            t.HasCheckConstraint("chk_oauth_audit_source", "source IN ('whoop', 'oura', 'strava', 'apple_health')");
                        });
                });

            modelBuilder.Entity("SomaCore.Domain.StravaActivities.StravaActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("activity_type");

                    b.Property<decimal?>("AverageCadence")
                        .HasColumnType("numeric")
                        .HasColumnName("average_cadence");

                    b.Property<int?>("AverageHr")
                        .HasColumnType("integer")
                        .HasColumnName("average_hr");

                    b.Property<decimal?>("AverageSpeedMps")
                        .HasColumnType("numeric")
                        .HasColumnName("average_speed_mps");

                    b.Property<decimal?>("AverageWatts")
                        .HasColumnType("numeric")
                        .HasColumnName("average_watts");

                    b.Property<decimal?>("Calories")
                        .HasColumnType("numeric")
                        .HasColumnName("calories");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset?>("DetailFetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detail_fetched_at");

                    b.Property<bool?>("DeviceWatts")
                        .HasColumnType("boolean")
                        .HasColumnName("device_watts");

                    b.Property<decimal?>("DistanceMeters")
                        .HasColumnType("numeric")
                        .HasColumnName("distance_meters");

                    b.Property<int>("ElapsedSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("elapsed_seconds");

                    b.Property<Guid?>("ExternalConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_connection_id");

                    b.Property<JsonDocument>("HrZones")
                        .HasColumnType("jsonb")
                        .HasColumnName("hr_zones");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("IngestedVia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ingested_via");

                    b.Property<int?>("KudosCount")
                        .HasColumnType("integer")
                        .HasColumnName("kudos_count");

                    b.Property<JsonDocument>("Laps")
                        .HasColumnType("jsonb")
                        .HasColumnName("laps");

                    b.Property<int?>("MaxHr")
                        .HasColumnType("integer")
                        .HasColumnName("max_hr");

                    b.Property<decimal?>("MaxSpeedMps")
                        .HasColumnType("numeric")
                        .HasColumnName("max_speed_mps");

                    b.Property<int?>("MaxWatts")
                        .HasColumnType("integer")
                        .HasColumnName("max_watts");

                    b.Property<int?>("MovingSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("moving_seconds");

                    b.Property<JsonDocument>("RawDetailPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_detail_payload");

                    b.Property<JsonDocument>("RawSummaryPayload")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_summary_payload");

                    b.Property<JsonDocument>("Splits")
                        .HasColumnType("jsonb")
                        .HasColumnName("splits");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<long>("StravaActivityId")
                        .HasColumnType("bigint")
                        .HasColumnName("strava_activity_id");

                    b.Property<long>("StravaAthleteId")
                        .HasColumnType("bigint")
                        .HasColumnName("strava_athlete_id");

                    b.Property<decimal?>("TotalElevationGainM")
                        .HasColumnType("numeric")
                        .HasColumnName("total_elevation_gain_m");

                    b.Property<string>("TraceId")
                        .HasColumnType("text")
                        .HasColumnName("trace_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int?>("WeightedAvgWatts")
                        .HasColumnType("integer")
                        .HasColumnName("weighted_avg_watts");

                    b.HasKey("Id")
                        .HasName("pk_strava_activities");

                    b.HasIndex("ExternalConnectionId")
                        .HasDatabaseName("ix_strava_activities_external_connection_id");

                    b.HasIndex("StravaActivityId")
                        .IsUnique()
                        .HasDatabaseName("idx_strava_activities_activity_id");

                    b.HasIndex("UserId", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_strava_activities_user_started");

                    b.ToTable("strava_activities", null, t =>
                        {
                            t.HasCheckConstraint("chk_strava_activities_avg_hr_range", "average_hr IS NULL OR (average_hr BETWEEN 0 AND 300)");

                            t.HasCheckConstraint("chk_strava_activities_elapsed_positive", "elapsed_seconds > 0");

                            t.HasCheckConstraint("chk_strava_activities_max_hr_range", "max_hr IS NULL OR (max_hr BETWEEN 0 AND 300)");
                        });
                });

            modelBuilder.Entity("SomaCore.Domain.UserDocuments.UserDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("text")
                        .HasColumnName("extracted_text");

                    b.Property<byte[]>("FileBytes")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("file_bytes");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<int>("FileSize")
                        .HasColumnType("integer")
                        .HasColumnName("file_size");

                    b.Property<string>("ParseError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("parse_error");

                    b.Property<string>("ParseStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parse_status");

                    b.Property<string>("Summary")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("summary");

                    b.Property<string>("TraceId")
                        .HasColumnType("text")
                        .HasColumnName("trace_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_documents");

                    b.HasIndex("UserId", "UploadedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_user_documents_user_uploaded");

                    b.ToTable("user_documents", null, t =>
                        {
                            t.HasCheckConstraint("chk_user_documents_file_size", "file_size > 0 AND file_size <= 10485760");

                            t.HasCheckConstraint("chk_user_documents_parse_status", "parse_status IN ('parsed', 'failed')");
                        });
                });

            modelBuilder.Entity("SomaCore.Domain.UserNotes.UserNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("ActiveUntil")
                        .HasColumnType("date")
                        .HasColumnName("active_until");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("TraceId")
                        .HasColumnType("text")
                        .HasColumnName("trace_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_notes");

                    b.HasIndex("UserId", "ActiveUntil")
                        .HasDatabaseName("idx_user_notes_user_active_until");

                    b.ToTable("user_notes", null, t =>
                        {
                            t.HasCheckConstraint("chk_user_notes_category", "category IS NULL OR category IN ('symptom', 'schedule', 'context')");

                            t.HasCheckConstraint("chk_user_notes_source", "source IN ('quick_log', 'conversation')");
                        });
                });

            modelBuilder.Entity("SomaCore.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AgentOptIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("agent_opt_in");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("EntraOid")
                        .HasColumnType("uuid")
                        .HasColumnName("entra_oid");

                    b.Property<Guid>("EntraTenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("entra_tenant_id");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .HasDatabaseName("idx_users_email");

                    b.HasIndex("EntraOid")
                        .IsUnique()
                        .HasDatabaseName("ix_users_entra_oid");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SomaCore.Domain.WebhookEvents.WebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<Guid?>("ExternalConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_connection_id");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("ProcessingAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("processing_attempts");

                    b.Property<DateTimeOffset?>("ProcessingStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processing_started_at");

                    b.Property<JsonDocument>("RawBody")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_body");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("SignatureHeader")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("signature_header");

                    b.Property<string>("SignatureTimestampHeader")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("signature_timestamp_header");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_event_id");

                    b.Property<string>("SourceTraceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_trace_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("received")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_webhook_events");

                    b.HasIndex("ExternalConnectionId")
                        .HasDatabaseName("ix_webhook_events_external_connection_id");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("idx_webhook_events_pending")
                        .HasFilter("status IN ('received', 'processing')");

                    b.HasIndex("UserId", "ReceivedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_webhook_events_user_received")
                        .HasFilter("user_id IS NOT NULL");

                    b.HasIndex("Source", "SourceEventId", "SourceTraceId")
                        .IsUnique()
                        .HasDatabaseName("idx_webhook_events_dedupe");

                    b.ToTable("webhook_events", null, t =>
                        {
                            t.HasCheckConstraint("chk_webhook_events_source", "source IN ('whoop', 'oura', 'strava')");

                            t.HasCheckConstraint("chk_webhook_events_status", "status IN ('received', 'processing', 'processed', 'failed', 'discarded')");
                        });
                });

            modelBuilder.Entity("SomaCore.Domain.WhoopRecoveries.WhoopRecovery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("CycleEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cycle_end_at");

                    b.Property<DateTimeOffset>("CycleStartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cycle_start_at");

                    b.Property<Guid?>("ExternalConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_connection_id");

                    b.Property<decimal?>("HrvRmssdMilli")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("hrv_rmssd_milli");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("IngestedVia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ingested_via");

                    b.Property<JsonDocument>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<int?>("RecoveryScore")
                        .HasColumnType("integer")
                        .HasColumnName("recovery_score");

                    b.Property<int?>("RestingHeartRate")
                        .HasColumnType("integer")
                        .HasColumnName("resting_heart_rate");

                    b.Property<string>("ScoreState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("score_state");

                    b.Property<decimal?>("SkinTempCelsius")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("skin_temp_celsius");

                    b.Property<decimal?>("Spo2Percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("spo2_percentage");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("WhoopCycleId")
                        .HasColumnType("bigint")
                        .HasColumnName("whoop_cycle_id");

                    b.Property<Guid?>("WhoopSleepId")
                        .HasColumnType("uuid")
                        .HasColumnName("whoop_sleep_id");

                    b.HasKey("Id")
                        .HasName("pk_whoop_recoveries");

                    b.HasIndex("WhoopSleepId")
                        .HasDatabaseName("idx_whoop_recoveries_sleep_id")
                        .HasFilter("whoop_sleep_id IS NOT NULL");

                    b.HasIndex("ExternalConnectionId", "WhoopCycleId")
                        .IsUnique()
                        .HasDatabaseName("idx_whoop_recoveries_connection_cycle");

                    b.HasIndex("UserId", "CycleStartAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_whoop_recoveries_user_cycle_start");

                    b.ToTable("whoop_recoveries", null, t =>
                        {
                            t.HasCheckConstraint("chk_whoop_recoveries_ingested_via", "ingested_via IN ('webhook', 'poller', 'on_open_pull', 'backfill')");

                            t.HasCheckConstraint("chk_whoop_recoveries_score_range", "recovery_score IS NULL OR (recovery_score BETWEEN 0 AND 100)");

                            t.HasCheckConstraint("chk_whoop_recoveries_score_state", "score_state IN ('SCORED', 'PENDING_SCORE', 'UNSCORABLE')");

                            t.HasCheckConstraint("chk_whoop_recoveries_scored_has_score", "(score_state = 'SCORED' AND recovery_score IS NOT NULL) OR (score_state IN ('PENDING_SCORE', 'UNSCORABLE'))");

                            t.HasCheckConstraint("chk_whoop_recoveries_spo2_range", "spo2_percentage IS NULL OR (spo2_percentage BETWEEN 0 AND 100)");
                        });
                });

            modelBuilder.Entity("SomaCore.Domain.WhoopSleeps.WhoopSleep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<Guid?>("ExternalConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_connection_id");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("IngestedVia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ingested_via");

                    b.Property<bool>("Nap")
                        .HasColumnType("boolean")
                        .HasColumnName("nap");

                    b.Property<JsonDocument>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<JsonDocument>("Score")
                        .HasColumnType("jsonb")
                        .HasColumnName("score");

                    b.Property<string>("ScoreState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("score_state");

                    b.Property<decimal?>("SleepConsistencyPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("sleep_consistency_percentage");

                    b.Property<decimal?>("SleepEfficiencyPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("sleep_efficiency_percentage");

                    b.Property<decimal?>("SleepPerformancePercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("sleep_performance_percentage");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<string>("TimezoneOffset")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone_offset");

                    b.Property<long?>("TotalInBedTimeMilli")
                        .HasColumnType("bigint")
                        .HasColumnName("total_in_bed_time_milli");

                    b.Property<long?>("TotalSleepTimeMilli")
                        .HasColumnType("bigint")
                        .HasColumnName("total_sleep_time_milli");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WhoopSleepId")
                        .HasColumnType("uuid")
                        .HasColumnName("whoop_sleep_id");

                    b.HasKey("Id")
                        .HasName("pk_whoop_sleeps");

                    b.HasIndex("ExternalConnectionId", "WhoopSleepId")
                        .IsUnique()
                        .HasDatabaseName("idx_whoop_sleeps_connection_sleep");

                    b.HasIndex("UserId", "StartAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_whoop_sleeps_user_start");

                    b.ToTable("whoop_sleeps", null, t =>
                        {
                            t.HasCheckConstraint("chk_whoop_sleeps_cons_range", "sleep_consistency_percentage IS NULL OR (sleep_consistency_percentage BETWEEN 0 AND 100)");

                            t.HasCheckConstraint("chk_whoop_sleeps_eff_range", "sleep_efficiency_percentage IS NULL OR (sleep_efficiency_percentage BETWEEN 0 AND 100)");

                            t.HasCheckConstraint("chk_whoop_sleeps_ingested_via", "ingested_via IN ('webhook', 'poller', 'on_open_pull', 'backfill')");

                            t.HasCheckConstraint("chk_whoop_sleeps_perf_range", "sleep_performance_percentage IS NULL OR (sleep_performance_percentage BETWEEN 0 AND 100)");

                            t.HasCheckConstraint("chk_whoop_sleeps_score_state", "score_state IN ('SCORED', 'PENDING_SCORE', 'UNSCORABLE')");
                        });
                });

            modelBuilder.Entity("SomaCore.Domain.WhoopWorkouts.WhoopWorkout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AverageHeartRate")
                        .HasColumnType("integer")
                        .HasColumnName("average_heart_rate");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<Guid?>("ExternalConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_connection_id");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("IngestedVia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ingested_via");

                    b.Property<decimal?>("Kilojoule")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("kilojoule");

                    b.Property<int?>("MaxHeartRate")
                        .HasColumnType("integer")
                        .HasColumnName("max_heart_rate");

                    b.Property<JsonDocument>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<JsonDocument>("Score")
                        .HasColumnType("jsonb")
                        .HasColumnName("score");

                    b.Property<string>("ScoreState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("score_state");

                    b.Property<string>("SportName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sport_name");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<decimal?>("Strain")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("strain");

                    b.Property<string>("TimezoneOffset")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("timezone_offset");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WhoopWorkoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("whoop_workout_id");

                    b.HasKey("Id")
                        .HasName("pk_whoop_workouts");

                    b.HasIndex("ExternalConnectionId", "WhoopWorkoutId")
                        .IsUnique()
                        .HasDatabaseName("idx_whoop_workouts_connection_workout");

                    b.HasIndex("UserId", "StartAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_whoop_workouts_user_start");

                    b.ToTable("whoop_workouts", null, t =>
                        {
                            t.HasCheckConstraint("chk_whoop_workouts_avg_hr_range", "average_heart_rate IS NULL OR (average_heart_rate BETWEEN 0 AND 300)");

                            t.HasCheckConstraint("chk_whoop_workouts_ingested_via", "ingested_via IN ('webhook', 'poller', 'on_open_pull', 'backfill')");

                            t.HasCheckConstraint("chk_whoop_workouts_max_hr_range", "max_heart_rate IS NULL OR (max_heart_rate BETWEEN 0 AND 300)");

                            t.HasCheckConstraint("chk_whoop_workouts_score_state", "score_state IN ('SCORED', 'PENDING_SCORE', 'UNSCORABLE')");

                            t.HasCheckConstraint("chk_whoop_workouts_strain_range", "strain IS NULL OR (strain BETWEEN 0 AND 21)");
                        });
                });

            modelBuilder.Entity("SomaCore.Domain.Agent.AgentInvocation", b =>
                {
                    b.HasOne("SomaCore.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_agent_invocations_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SomaCore.Domain.CoachThreads.CoachMessage", b =>
                {
                    b.HasOne("SomaCore.Domain.CoachThreads.CoachThread", "Thread")
                        .WithMany("Messages")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coach_messages_coach_threads_thread_id");

                    b.HasOne("SomaCore.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coach_messages_users_user_id");

                    b.Navigation("Thread");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SomaCore.Domain.CoachThreads.CoachThread", b =>
                {
                    b.HasOne("SomaCore.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_coach_threads_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SomaCore.Domain.ExternalConnections.ExternalConnection", b =>
                {
                    b.HasOne("SomaCore.Domain.Users.User", "User")
                        .WithMany("ExternalConnections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_external_connections_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SomaCore.Domain.FoodEntries.FoodEntry", b =>
                {
                    b.HasOne("SomaCore.Domain.ExternalConnections.ExternalConnection", "ExternalConnection")
                        .WithMany()
                        .HasForeignKey("ExternalConnectionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_mfp_food_entries_external_connections_external_connection_id");

                    b.HasOne("SomaCore.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mfp_food_entries_users_user_id");

                    b.Navigation("ExternalConnection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SomaCore.Domain.HealthKitWorkouts.HealthKitWorkout", b =>
                {
                    b.HasOne("SomaCore.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_healthkit_workouts_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SomaCore.Domain.LabUploads.LabBiomarker", b =>
                {
                    b.HasOne("SomaCore.Domain.LabUploads.LabUpload", "LabUpload")
                        .WithMany("Biomarkers")
                        .HasForeignKey("LabUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lab_biomarkers_lab_uploads_lab_upload_id");

                    b.HasOne("SomaCore.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lab_biomarkers_users_user_id");

                    b.Navigation("LabUpload");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SomaCore.Domain.LabUploads.LabUpload", b =>
                {
                    b.HasOne("SomaCore.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lab_uploads_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SomaCore.Domain.OAuthAudit.OAuthAuditEntry", b =>
                {
                    b.HasOne("SomaCore.Domain.ExternalConnections.ExternalConnection", "ExternalConnection")
                        .WithMany()
                        .HasForeignKey("ExternalConnectionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_oauth_audit_external_connections_external_connection_id");

                    b.HasOne("SomaCore.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_oauth_audit_users_user_id");

                    b.Navigation("ExternalConnection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SomaCore.Domain.StravaActivities.StravaActivity", b =>
                {
                    b.HasOne("SomaCore.Domain.ExternalConnections.ExternalConnection", "ExternalConnection")
                        .WithMany()
                        .HasForeignKey("ExternalConnectionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_strava_activities_external_connections_external_connection_");

                    b.HasOne("SomaCore.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_strava_activities_users_user_id");

                    b.Navigation("ExternalConnection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SomaCore.Domain.UserDocuments.UserDocument", b =>
                {
                    b.HasOne("SomaCore.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_documents_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SomaCore.Domain.UserNotes.UserNote", b =>
                {
                    b.HasOne("SomaCore.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_notes_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SomaCore.Domain.WebhookEvents.WebhookEvent", b =>
                {
                    b.HasOne("SomaCore.Domain.ExternalConnections.ExternalConnection", "ExternalConnection")
                        .WithMany()
                        .HasForeignKey("ExternalConnectionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_webhook_events_external_connections_external_connection_id");

                    b.HasOne("SomaCore.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_webhook_events_users_user_id");

                    b.Navigation("ExternalConnection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SomaCore.Domain.WhoopRecoveries.WhoopRecovery", b =>
                {
                    b.HasOne("SomaCore.Domain.ExternalConnections.ExternalConnection", "ExternalConnection")
                        .WithMany("WhoopRecoveries")
                        .HasForeignKey("ExternalConnectionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_whoop_recoveries_external_connections_external_connection_id");

                    b.HasOne("SomaCore.Domain.Users.User", "User")
                        .WithMany("WhoopRecoveries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_whoop_recoveries_users_user_id");

                    b.Navigation("ExternalConnection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SomaCore.Domain.WhoopSleeps.WhoopSleep", b =>
                {
                    b.HasOne("SomaCore.Domain.ExternalConnections.ExternalConnection", "ExternalConnection")
                        .WithMany()
                        .HasForeignKey("ExternalConnectionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_whoop_sleeps_external_connections_external_connection_id");

                    b.HasOne("SomaCore.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_whoop_sleeps_users_user_id");

                    b.Navigation("ExternalConnection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SomaCore.Domain.WhoopWorkouts.WhoopWorkout", b =>
                {
                    b.HasOne("SomaCore.Domain.ExternalConnections.ExternalConnection", "ExternalConnection")
                        .WithMany()
                        .HasForeignKey("ExternalConnectionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_whoop_workouts_external_connections_external_connection_id");

                    b.HasOne("SomaCore.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_whoop_workouts_users_user_id");

                    b.Navigation("ExternalConnection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SomaCore.Domain.CoachThreads.CoachThread", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("SomaCore.Domain.ExternalConnections.ExternalConnection", b =>
                {
                    b.Navigation("WhoopRecoveries");
                });

            modelBuilder.Entity("SomaCore.Domain.LabUploads.LabUpload", b =>
                {
                    b.Navigation("Biomarkers");
                });

            modelBuilder.Entity("SomaCore.Domain.Users.User", b =>
                {
                    b.Navigation("ExternalConnections");

                    b.Navigation("WhoopRecoveries");
                });
#pragma warning restore 612, 618
        }
    }
}
