// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SomaCore.Infrastructure.Persistence;

#nullable disable

namespace SomaCore.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SomaCoreDbContext))]
    partial class SomaCoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SomaCore.Domain.ExternalConnections.ExternalConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonDocument>("ConnectionMetadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("connection_metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("KeyVaultSecretName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_vault_secret_name");

                    b.Property<DateTimeOffset?>("LastRefreshAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_refresh_at");

                    b.Property<string>("LastRefreshError")
                        .HasColumnType("text")
                        .HasColumnName("last_refresh_error");

                    b.Property<DateTimeOffset?>("NextRefreshAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_refresh_at");

                    b.Property<int>("RefreshFailureCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("refresh_failure_count");

                    b.PrimitiveCollection<string[]>("Scopes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("scopes")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_external_connections");

                    b.HasIndex("NextRefreshAt")
                        .HasDatabaseName("idx_external_connections_next_refresh")
                        .HasFilter("status = 'active'");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_external_connections_user_id");

                    b.HasIndex("UserId", "Source")
                        .IsUnique()
                        .HasDatabaseName("idx_external_connections_user_source_active")
                        .HasFilter("status = 'active'");

                    b.ToTable("external_connections", null, t =>
                        {
                            t.HasCheckConstraint("chk_external_connections_kv_secret_name_not_empty", "length(key_vault_secret_name) > 0");

                            t.HasCheckConstraint("chk_external_connections_source", "source IN ('whoop', 'oura', 'strava', 'apple_health', 'manual')");

                            t.HasCheckConstraint("chk_external_connections_status", "status IN ('active', 'revoked', 'refresh_failed', 'pending_authorization')");
                        });
                });

            modelBuilder.Entity("SomaCore.Domain.OAuthAudit.OAuthAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<JsonDocument>("Context")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("context")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<Guid?>("ExternalConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_connection_id");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("http_status_code");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_oauth_audit");

                    b.HasIndex("ExternalConnectionId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_oauth_audit_connection_occurred")
                        .HasFilter("external_connection_id IS NOT NULL");

                    b.HasIndex("UserId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_oauth_audit_user_occurred")
                        .HasFilter("user_id IS NOT NULL");

                    b.ToTable("oauth_audit", null, t =>
                        {
                            t.HasCheckConstraint("chk_oauth_audit_action", "action IN ('authorize', 'callback_success', 'callback_failed', 'token_refresh_success', 'token_refresh_failed', 'revoke_detected', 'manual_disconnect')");

                            t.HasCheckConstraint("chk_oauth_audit_source", "source IN ('whoop', 'oura', 'strava', 'apple_health')");
                        });
                });

            modelBuilder.Entity("SomaCore.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("EntraOid")
                        .HasColumnType("uuid")
                        .HasColumnName("entra_oid");

                    b.Property<Guid>("EntraTenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("entra_tenant_id");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .HasDatabaseName("idx_users_email");

                    b.HasIndex("EntraOid")
                        .IsUnique()
                        .HasDatabaseName("ix_users_entra_oid");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SomaCore.Domain.WebhookEvents.WebhookEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<Guid?>("ExternalConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_connection_id");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("ProcessingAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("processing_attempts");

                    b.Property<DateTimeOffset?>("ProcessingStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processing_started_at");

                    b.Property<JsonDocument>("RawBody")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_body");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("SignatureHeader")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("signature_header");

                    b.Property<string>("SignatureTimestampHeader")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("signature_timestamp_header");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("SourceEventId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_event_id");

                    b.Property<string>("SourceTraceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_trace_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("received")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_webhook_events");

                    b.HasIndex("ExternalConnectionId")
                        .HasDatabaseName("ix_webhook_events_external_connection_id");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("idx_webhook_events_pending")
                        .HasFilter("status IN ('received', 'processing')");

                    b.HasIndex("UserId", "ReceivedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_webhook_events_user_received")
                        .HasFilter("user_id IS NOT NULL");

                    b.HasIndex("Source", "SourceEventId", "SourceTraceId")
                        .IsUnique()
                        .HasDatabaseName("idx_webhook_events_dedupe");

                    b.ToTable("webhook_events", null, t =>
                        {
                            t.HasCheckConstraint("chk_webhook_events_source", "source IN ('whoop', 'oura', 'strava')");

                            t.HasCheckConstraint("chk_webhook_events_status", "status IN ('received', 'processing', 'processed', 'failed', 'discarded')");
                        });
                });

            modelBuilder.Entity("SomaCore.Domain.WhoopRecoveries.WhoopRecovery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("CycleEndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cycle_end_at");

                    b.Property<DateTimeOffset>("CycleStartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cycle_start_at");

                    b.Property<Guid>("ExternalConnectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_connection_id");

                    b.Property<decimal?>("HrvRmssdMilli")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("hrv_rmssd_milli");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("IngestedVia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ingested_via");

                    b.Property<JsonDocument>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_payload");

                    b.Property<int?>("RecoveryScore")
                        .HasColumnType("integer")
                        .HasColumnName("recovery_score");

                    b.Property<int?>("RestingHeartRate")
                        .HasColumnType("integer")
                        .HasColumnName("resting_heart_rate");

                    b.Property<string>("ScoreState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("score_state");

                    b.Property<decimal?>("SkinTempCelsius")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("skin_temp_celsius");

                    b.Property<decimal?>("Spo2Percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("spo2_percentage");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("WhoopCycleId")
                        .HasColumnType("bigint")
                        .HasColumnName("whoop_cycle_id");

                    b.Property<Guid?>("WhoopSleepId")
                        .HasColumnType("uuid")
                        .HasColumnName("whoop_sleep_id");

                    b.HasKey("Id")
                        .HasName("pk_whoop_recoveries");

                    b.HasIndex("WhoopSleepId")
                        .HasDatabaseName("idx_whoop_recoveries_sleep_id")
                        .HasFilter("whoop_sleep_id IS NOT NULL");

                    b.HasIndex("ExternalConnectionId", "WhoopCycleId")
                        .IsUnique()
                        .HasDatabaseName("idx_whoop_recoveries_connection_cycle");

                    b.HasIndex("UserId", "CycleStartAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_whoop_recoveries_user_cycle_start");

                    b.ToTable("whoop_recoveries", null, t =>
                        {
                            t.HasCheckConstraint("chk_whoop_recoveries_ingested_via", "ingested_via IN ('webhook', 'poller', 'on_open_pull')");

                            t.HasCheckConstraint("chk_whoop_recoveries_score_range", "recovery_score IS NULL OR (recovery_score BETWEEN 0 AND 100)");

                            t.HasCheckConstraint("chk_whoop_recoveries_score_state", "score_state IN ('SCORED', 'PENDING_SCORE', 'UNSCORABLE')");

                            t.HasCheckConstraint("chk_whoop_recoveries_scored_has_score", "(score_state = 'SCORED' AND recovery_score IS NOT NULL) OR (score_state IN ('PENDING_SCORE', 'UNSCORABLE'))");

                            t.HasCheckConstraint("chk_whoop_recoveries_spo2_range", "spo2_percentage IS NULL OR (spo2_percentage BETWEEN 0 AND 100)");
                        });
                });

            modelBuilder.Entity("SomaCore.Domain.ExternalConnections.ExternalConnection", b =>
                {
                    b.HasOne("SomaCore.Domain.Users.User", "User")
                        .WithMany("ExternalConnections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_external_connections_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SomaCore.Domain.OAuthAudit.OAuthAuditEntry", b =>
                {
                    b.HasOne("SomaCore.Domain.ExternalConnections.ExternalConnection", "ExternalConnection")
                        .WithMany()
                        .HasForeignKey("ExternalConnectionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_oauth_audit_external_connections_external_connection_id");

                    b.HasOne("SomaCore.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_oauth_audit_users_user_id");

                    b.Navigation("ExternalConnection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SomaCore.Domain.WebhookEvents.WebhookEvent", b =>
                {
                    b.HasOne("SomaCore.Domain.ExternalConnections.ExternalConnection", "ExternalConnection")
                        .WithMany()
                        .HasForeignKey("ExternalConnectionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_webhook_events_external_connections_external_connection_id");

                    b.HasOne("SomaCore.Domain.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_webhook_events_users_user_id");

                    b.Navigation("ExternalConnection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SomaCore.Domain.WhoopRecoveries.WhoopRecovery", b =>
                {
                    b.HasOne("SomaCore.Domain.ExternalConnections.ExternalConnection", "ExternalConnection")
                        .WithMany("WhoopRecoveries")
                        .HasForeignKey("ExternalConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_whoop_recoveries_external_connections_external_connection_id");

                    b.HasOne("SomaCore.Domain.Users.User", "User")
                        .WithMany("WhoopRecoveries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_whoop_recoveries_users_user_id");

                    b.Navigation("ExternalConnection");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SomaCore.Domain.ExternalConnections.ExternalConnection", b =>
                {
                    b.Navigation("WhoopRecoveries");
                });

            modelBuilder.Entity("SomaCore.Domain.Users.User", b =>
                {
                    b.Navigation("ExternalConnections");

                    b.Navigation("WhoopRecoveries");
                });
#pragma warning restore 612, 618
        }
    }
}
